//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegalManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Calendar
    {
        public int Id { get; set; }
        [Required]
        [Display(Name = "Calendar Title")]
        public string Title { get; set; }
        [Required]
        [Display(Name = "From ")]
        [DataType(DataType.Date)]
        public System.DateTime From { get; set; }
        //[Required]
        [Display(Name = "To ")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> To { get; set; }
        [Required]
        [Display(Name = "Case Number ")]
        //[DataType(DataType.Date)]
        public string MatterNumber { get; set; }
        [Required]
        [Display(Name = "Advocate ")]
        public string StaffId { get; set; }
        //[Required]
        [Display(Name = "Location ")]
        //[DataType(DataType.Date)]
        public string Locations { get; set; }
        public string Priority { get; set; }
        [Display(Name = "Meeting Type ")]
        public string MeetingType { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
