//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegalManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calendar
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public System.DateTime From { get; set; }
        public Nullable<System.DateTime> To { get; set; }
        public string MatterNumber { get; set; }
        public string StaffId { get; set; }
        public string Locations { get; set; }
        public string Priority { get; set; }
        public string MeetingType { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
