//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegalManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Calendar
    {
        public int Id { get; set; }
        [Required]
        [Display(Name ="Calendar Title *")]
        public string Title { get; set; }
        [Required]
        [Display(Name = "From *")]
        [DataType(DataType.Date)]
        public System.DateTime From { get; set; }
        [Required]
        [Display(Name = "To *")]
        [DataType(DataType.Date)]
        public DateTime To { get; set; }
        [Required]
        [Display(Name = "Matter Number *")]
        //[DataType(DataType.Date)]
        public string MatterNumber { get; set; }
        [Required]
        [Display(Name = "Advocate *")]
        //[DataType(DataType.Date)]
        public string StaffId { get; set; }
        public string Locations { get; set; }
        public string Priority { get; set; }
        //[Required]
        [Display(Name = "Meeting Type *")]
        //[DataType(DataType.Date)]
        public string MeetingType { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime ModifiedOn { get; set; }
    }
}
