//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegalManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Certification
    {
        public int Id { get; set; }
        [Required]
        [Display(Name = "Certification Name")]
        public string Name { get; set; }
        [DataType(DataType.MultilineText)]
        [Display(Name = "Description")]
        public string Description { get; set; }
        //[DataType(DataType.Date)]
        [Display(Name = "Certification Type")]
        public string CertificationType { get; set; }
        [DataType(DataType.Date)]
        [Display(Name = "Date Achieved")]
        public Nullable<System.DateTime> DateAchieved { get; set; }
        public string Skilled { get; set; }
        public string StaffId { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModeifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
