//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegalManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Client
    {
        public int ClientId { get; set; }
        [Required]
        [Display(Name = "First Name ")]
        public string FirstName { get; set; }
        [Display(Name = "Middle Name ")]
        public string MiddleName { get; set; }
        [Required]
        [Display(Name = "Last Name ")]
        public string LastName { get; set; }
        [Required]
        [Display(Name = "Email Address")]
        [DataType(DataType.EmailAddress)]
        public string EmailAddress { get; set; }
        [Required]
        [Display(Name = "Phone Number ")]
        public string PhoneNumber { get; set; }
        //[Required]
        [Display(Name = "Client Address")]
        [DataType(DataType.MultilineText)]
        public string Address { get; set; }
        public string Town { get; set; }
        [Display(Name = "Postal Code")]
        public string PostalCode { get; set; }
        public string Website { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    }
}
