//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegalManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientMatterAcceptanceForm
    {
        public int Id { get; set; }
        public Nullable<int> ClientId { get; set; }
        public string Description { get; set; }
        public string Industry { get; set; }
        public Nullable<double> AgreedFee { get; set; }
        public string PaymentTerms { get; set; }
        public Nullable<int> TimeFrame { get; set; }
        public string MatterManager { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
