//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegalManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourtActivity
    {
        public int Id { get; set; }
        public string MatterNumber { get; set; }
        public System.DateTime DateHeared { get; set; }
        public string CourtName { get; set; }
        public string Location { get; set; }
        public string StaffId { get; set; }
        public string Status { get; set; }
        public string AdvocateArgument { get; set; }
        public string OpponentArgument { get; set; }
        public string AdvocateNote { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.DateTime> DateAdjourned { get; set; }
        public string DefenseCounselName { get; set; }
    
        public virtual Matter Matter { get; set; }
    }
}
