//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegalManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Education
    {
        public int Id { get; set; }
        [Display(Name = "School Name")]
        //[DataType(DataType.Date)]
        [Required]
        public string School { get; set; }
        [Display(Name = "Date Start")]
        [DataType(DataType.Date)]
        [Required]
        public System.DateTime DateStart { get; set; }
        [Display(Name = "End Date")]
        [DataType(DataType.Date)]
        [Required]
        public DateTime EndDate { get; set; }
        public string Major { get; set; }
        [Display(Name = "Date Awarded")]
        [DataType(DataType.Date)]
        [Required]
        public DateTime DateAwarded { get; set; }
        public bool Graduated { get; set; }
        public string Qualification { get; set; }
        public string Description { get; set; }
        public string Grade { get; set; }
        public string StaffId { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime ModifiedOn { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
