//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegalManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education
    {
        public int Id { get; set; }
        public string School { get; set; }
        public System.DateTime DateStart { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Major { get; set; }
        public Nullable<System.DateTime> DateAwarded { get; set; }
        public Nullable<bool> Graduated { get; set; }
        public string Qualification { get; set; }
        public string Description { get; set; }
        public string Grade { get; set; }
        public string StaffId { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
