//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegalManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Experience
    {
        public int Id { get; set; }
        [Required]
        [Display(Name ="Employer *")]
        public string Employer { get; set; }
        [Display(Name ="Designation *")]
        public string Designation { get; set; }
        [Display(Name ="Start Date *")]
        [DataType(DataType.Date)]
        public System.DateTime StartDate { get; set; }
        [Display(Name = "End Date *")]
        [DataType(DataType.Date)]
        public System.DateTime EndDate { get; set; }
        public string Description { get; set; }
        public double Salary { get; set; }
        public string StaffId { get; set; }
        public DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime ModifiedOn { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
