//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegalManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class File
    {
        public int Id { get; set; }
        [Required]
        [Display(Name ="File Number")]
        public string FileNumber { get; set; }
        [Required]
        [Display(Name = "File Name")]
        public string FileName { get; set; }
        //[Required]
        [Display(Name = "File Type")]
        public string FileType { get; set; }
        [Display(Name ="Client Name")]
        public int ClientId { get; set; }
        [Required]
        [Display(Name = "Opening Date")]
        [DataType(DataType.Date)]
        public DateTime OpeningDate { get; set; }
        [Display(Name ="Location")]
        public string FilePath { get; set; }
        [Display(Name ="Advocate Name")]
        public string AdvocateId { get; set; }
        //[Required]
        [Display(Name = "Closing Date")]
        [DataType(DataType.Date)]
        public DateTime ClosingDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime ModifiedOn { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
