//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegalManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Judgement
    {
        public int Id { get; set; }
        public string CaseTitle { get; set; }
        public Nullable<System.DateTime> DateDelivered { get; set; }
        public string JudgementPassed { get; set; }
        public string CourtName { get; set; }
    }
}
