//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegalManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class LicenseTable
    {
        public int Id { get; set; }
        [Required]
        [Display(Name = "Client Name")]
        public string ClientName { get; set; }
        //[Required]
        [Display(Name = "Software Version")]
        public string SoftwareVersion { get; set; }
        [Required]
        [Display(Name = "Approved Key")]
        public string ApprovedKey { get; set; }
        [Required]
        [Display(Name = "Validity From")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        [DataType(DataType.Date)]
        public System.DateTime ValidityFrom { get; set; }
        [Required]
        [Display(Name = "Validity To")]
        [DataType(DataType.Date)]
        public System.DateTime ValidityTo { get; set; }
        [Display(Name = "Approved Document")]
        public string ApprovedDocument { get; set; }
        [Required]
        [Display(Name = "Approved By")]
        public string ApprovedBy { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsLicensed { get; set; }
        public Nullable<bool> IsExpired { get; set; }
    }
}
