//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegalManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LicenseTable
    {
        public int Id { get; set; }
        public string ClientName { get; set; }
        public string SoftwareVersion { get; set; }
        public string ApprovedKey { get; set; }
        public System.DateTime ValidityFrom { get; set; }
        public System.DateTime ValidityTo { get; set; }
        public string ApprovedDocument { get; set; }
        public string ApprovedBy { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsLicensed { get; set; }
        public Nullable<bool> IsExpired { get; set; }
    }
}
