//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegalManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LMSTask
    {
        public int Id { get; set; }
        public string TaskType { get; set; }
        public string Description { get; set; }
        public string MatterNumber { get; set; }
        public int NotifyDays { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string Priority { get; set; }
        public string Reporter { get; set; }
        public Nullable<int> AdvocateGroupId { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
    
        public virtual Matter Matter { get; set; }
    }
}
