//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegalManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class LMSTask
    {
        public int Id { get; set; }
        [Required]
        [Display(Name = "Task Type")]
        public string TaskType { get; set; }
        //[Required]
        [Display(Name = "Task Description")]
        public string Description { get; set; }
        [Required]
        [Display(Name = "Case Number")]
        public string MatterNumber { get; set; }
        [Display(Name = "Notify me in ")]
        public int NotifyDays { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string Priority { get; set; }
        public string Reporter { get; set; }
        [Required]
        [Display(Name = "Advocate")]
        public Nullable<int> AdvocateGroupId { get; set; }
        [DataType(DataType.Date)]
        [Display(Name = "Due Date")]
        public Nullable<System.DateTime> DueDate { get; set; }
    }
}
