//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegalManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Matter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Matter()
        {
            this.Documents = new HashSet<Document>();
        }
    
        public int Id { get; set; }
        [Display(Name = "Case Title")]
        [Required]
        public string Subject { get; set; }
        public string Description { get; set; }
        [Display(Name = "Area of Practice")]
        public string AreaOfPractice { get; set; }
        [Display(Name = "Client Name")]
        [Required]
        public Nullable<int> ClientId { get; set; }
        [Display(Name = "Arrival Date")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> ArrivalDate { get; set; }
        [Display(Name = "Filed On")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> FiledOn { get; set; }
        [Display(Name = "Due Date")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> DueDate { get; set; }
        [Display(Name = "Case Number")]
        [Required]
        public string MatterNumber { get; set; }
        public string Priority { get; set; }
        [Display(Name = "Case Stage")]
        public string MatterStage { get; set; }
        [Display(Name = "Requested By")]
        public string RequestedBy { get; set; }
        [Display(Name = "Case Value")]
        public string MatterValue { get; set; }
        [Display(Name = "Estimated Effort")]
        public string EstimatedEffort { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string CaseNumber { get; set; }
        [Display(Name = "Line Manager")]
        public Nullable<int> LineManagerId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Documents { get; set; }
    }
}
