//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegalManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Matter
    {
        public int Id { get; set; }
        [Required]
        [Display(Name ="Subject *")]
        public string Subject { get; set; }
        [Display(Name ="Description *")]
        [Required]
        public string Description { get; set; }
        [Display(Name ="Practice Area")]
        public string AreaOfPractice { get; set; }
        [Required]
        [Display(Name ="Client Name *")]
        public int ClientId { get; set; }
        [Required]
        [Display(Name ="Advocate on the Matter")]
        public string StaffId { get; set; }
        public string Assignee { get; set; }
        [Required]
        [Display(Name ="Arrival Date")]
        [DataType(DataType.Date)]
        public DateTime ArrivalDate { get; set; }
        [Required]
        [Display(Name = "Filed On *")]
        [DataType(DataType.Date)]
        public DateTime FiledOn { get; set; }
        //[Required]
        [Display(Name = "Due Date *")]
        [DataType(DataType.Date)]
        public DateTime DueDate { get; set; }
        [Required]
        [Display(Name ="Matter Number")]
        public string MatterNumber { get; set; }
        public string Priority { get; set; }
        //[Required]
        [Display(Name = "Matter Stage")]
        //[DataType(DataType.Date)]
        public string MatterStage { get; set; }
        //[Required]
        [Display(Name = "Requested By")]
        //[DataType(DataType.Date)]
        public string RequestedBy { get; set; }
        //[Required]
        [Display(Name = "Matter Value")]
        //[DataType(DataType.Date)]
        public string MatterValue { get; set; }
        //[Required]
        [Display(Name = "Estimated Effort")]
        //[DataType(DataType.Date)]
        public string EstimatedEffort { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime ModifiedOn { get; set; }
    }
}
